server.port: 8080
server.compression.enabled: true
server.compression.mime-types: application/json,text/html,text/xml,text/plain,application/javascript,text/css

APP_NAME: dolly
APP_VERSION: ${application.version}
AAD_ISSUER_URI: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b

CLIENT_ID: f0174d28-cb33-44f9-a7b5-09e52582e601
UDI_STUB_CLIENT_ID: ${UDI_CLIENT_ID}

CLIENT_SECRET: ${azure.app.client.secret}

consumers:
  testnav-helsepersonell-service:
    name: testnav-helsepersonell-service
    namespace: dolly
    url: https://testnav-helsepersonell-service.dev.intern.nav.no
    cluster: dev-gcp

  testnav-organisasjon-forvalter:
    name: testnav-organisasjon-forvalter
    namespace: dolly
    url: https://testnav-organisasjon-forvalter.dev.intern.nav.no
    cluster: dev-gcp

#### APP DB ####
? app.datasource.onsHosts

springfox:
  documentation:
    swagger:
      v2:
        path: /internal/swagger-spec

dolly:
  api:
    v1:
      name: Dolly V2.0
      description: Dolly er verktøyet som kloner GDPR testdata til ønsket miljø. </br>
        Opprett fiktive testpersoner med arbeidsforhold, inntekter, sykemelding og annet i hht testbehov.
      version: Versjon 1
      header:
        nav-consumer-id: Navn på applikasjon som gjør kallet
        nav-call-id: Unik identifikator, typisk UUID (128 bit)

spring:
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/v2.0
          #The client_id of this application
          accepted-audience: ${CLIENT_ID}, api://${CLIENT_ID}

management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /internal
      exposure.include: prometheus,heapdump
      path-mapping.prometheus: metrics
  endpoint:
    prometheus.enabled: true
    heapdump.enabled: true
  metrics.export:
    prometheus.enabled: true