server.port: 8080
server.compression.enabled: true
server.compression.mime-types: application/json,text/html,text/xml,text/plain,application/javascript,text/css

APP_NAME: dolly
APP_VERSION: ${application.version}

#### APP DB ####
? app.datasource.onsHosts

springfox:
  documentation:
    swagger:
      v2:
        path: /internal/swagger-spec

dolly:
  api:
    v1:
      name: API versjon 1
      description: Dolly er en kloningsklient for NAVs personopplysning. Bruk den til å opprette fiktive testpersoner med fiktive inntekter og arbeidsforhold.
      header:
        nav-consumer-id: En ID for systemet som gjør kallet, som regel servicebrukeren til applikasjonen.
        nav-call-id: En ID som identifiserer kallkjeden som dette kallet er en del av.

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/v2.0
          #The client_id of this application
          accepted-audience: ${client.id}, api://${client.id}

management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /internal
      exposure.include: prometheus,heapdump
      path-mapping.prometheus: metrics
  endpoint:
    prometheus.enabled: true
    heapdump.enabled: true
  metrics.export:
    prometheus.enabled: true