apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dolly-backend-dev
  namespace: dolly
  labels:
    team: dolly
spec:
  accessPolicy:
    inbound:
      rules:
        - application: dolly-frontend-dev
        - application: testnorge-oversikt-frontend
  webproxy: true
  azure:
    application:
      enabled: true
  image: {{ image }}
  replicas:
    min: 1
    max: 2
  port: 8080
  ingresses:
    - https://dolly-backend-dev.dev.adeo.no
  liveness:
    path: /internal/isAlive
    initialDelay: 20
    periodSeconds: 2
    failureThreshold: 140
  readiness:
    path: /internal/isReady
    initialDelay: 20
    periodSeconds: 2
    failureThreshold: 140
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    requests:
      cpu: 1000m
      memory: 1024Mi
    limits:
      cpu: 1500m
      memory: 2048Mi
  vault:
    enabled: true
    paths:
      - kvPath: /kv/preprod/fss/dolly-backend-dev/dolly
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /oracle/data/dev/creds/dollybackend_t2-user
        mountPath: /var/run/secrets/nais.io/db
      - kvPath: /oracle/data/dev/config/dollybackend_t2
        mountPath: /var/run/secrets/nais.io/dbPath
