apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dolly-backend
  namespace: t1
  labels:
    team: registre
replicas:
  min: 2
  max: 2
spec:
  port: 8080
  ingresses:
    - https://dolly-backend-t1.nais.preprod.local
  liveness:
    path: /internal/isAlive
    initialDelay: 20
    periodSeconds: 2
    failureThreshold: 140
  readiness:
    path: /internal/isReady
    initialDelay: 20
    periodSeconds: 2
    failureThreshold: 140
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    requests:
      cpu: 1000m
      memory: 1024Mi
    limits:
      cpu: 1500m
      memory: 2048Mi
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/dev/config/dolly_t1
        mountPath: /var/run/secrets/nais.io/dbPath
      - kvPath: /oracle/data/dev/creds/dolly_t1-user
        mountPath: /var/run/secrets/nais.io/db
