apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dolly-backend
  namespace: u2
  labels:
    team: registre
replicas:
  min: 2
  max: 2
spec:
  port: 8080
  ingresses:
    - https://dolly-backend-u2.nais.preprod.local
  liveness:
    path: /internal/isAlive
    initialDelay: 20
    periodSeconds: 2
    failureThreshold: 140
  readiness:
    path: /internal/isReady
    initialDelay: 20
    periodSeconds: 2
    failureThreshold: 140
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    requests:
      cpu: 1000m
      memory: 1024Mi
    limits:
      cpu: 1500m
      memory: 2048Mi
  vault:
    enabled: true
    paths:
      - kvPath: /kv/preprod/fss/dolly-backend/u2
        mountPath: /var/run/secrets/nais.io/vault
fasitResources:
  used:
    - alias: dolly-backend-oidc
      resourceType: OpenIdConnect
      propertyMap:
        agentName: freg.security.oidc.idp.openam.clientId
        password: freg.security.oidc.idp.openam.clientSecret
        hostUrl: freg.security.oidc.idp.openam.hostUrl
        issuerUrl: freg.security.oidc.idp.openam.issuerUrl
        jwksUrl: freg.security.oidc.idp.openam.jwksUrl

    - alias: srvdolly-test-env
      resourceType: credential
      propertyMap:
        username: credentials.testEnv.username
        password: credentials.testEnv.password

    - alias: srvdolly-preprod-env
      resourceType: credential
      propertyMap:
        username: credentials.preprodEnv.username
        password: credentials.preprodEnv.password

    - alias: srvJiraDolly
      resourceType: credential
      propertyMap:
        username: jira.username
        password: jira.password

    - alias: dollyDB
      resourceType: DataSource
      propertyMap:
        url: spring.datasource.url
        username: spring.datasource.username
        password: spring.datasource.password
        onsHosts: app.datasource.onsHosts

    - alias: dolly-backend.application.properties
      resourceType: ApplicationProperties

  exposed:
    - alias: dolly-backend.api.v1
      resourceType: restservice
      path: /api/v1