### FREG-SECURITY ###
freg.security.oidc.enabled: true

fasit:
  url: https://fasit.adeo.no
  environment.name: u2

spring:
  flyway:
    enabled: false # Disabled by default as you should probably think twice before running Flyway-migrations