# Eksempelfil om hvordan "application-h2.yaml" skal se ut.

APP_NAME: dolly
FASIT_ENVIRONMENT_NAME: localhost

spring:
  datasource:
    url: jdbc:h2:mem:dollyDB
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    enabled: false
    url: jdbc:h2:mem:dollyDB;DB_CLOSE_DELAY=-1
    user: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2

freg.security.oidc:
  auth:
   header-filter-enabled: false
   cookie-filter-enabled: true
  login:
    enabled: true
    path: /login
  refresh:
    enabled: true
    cookie-filter.enabled: true
    remaining-seconds: 3600


#security:
#  oidc:
#    host: identity-provider server url
#    clientSecret: KLientpassordet til app
#security.oidc.secured-path: api/**


# abac.url:  Url til abac server
# no.nav.abac.systemuser.username: abac brukernavn
# no.nav.abac.systemuser.password: abac passord

#dolly.security.cors.origins: tillatte domener.

### TPSF ###
tpsf.server.url: https://tps-forvalteren-u2.nais.preprod.local
