freg.security.oidc.idp.openAm:
  hostUrl: https://isso-t.adeo.no:443/isso
  issuerUrl: https://isso-t.adeo.no:443/isso/oauth2
  jwksUrl: https://isso-t.adeo.no/isso/oauth2/connect/jwk_uri

freg.security.oidc.idp.navSts:
  hostUrl: https://security-token-service-q4.nais.preprod.local
  issuerUrl: https://security-token-service-q4.nais.preprod.local
  jwksUrl: https://security-token-service-q4.nais.preprod.local/rest/v1/sts/jwks

### FREG-SECURITY ###
freg.security.oidc.enabled: true

providers:
  fasit:
    url: https://fasit.adeo.no

fasit:
  url: https://fasit.adeo.no
  environment.name: u2

spring:
  flyway:
    enabled: false # Disabled by default as you should probably think twice before running Flyway-migrations