server.port: 8080
server.compression.enabled: true
server.compression.mime-types: application/json,text/html,text/xml,text/plain,application/javascript,text/css

APP_NAME: dolly
APP_VERSION: ${application.version}
