server.port: 8080
server.compression.enabled: true
server.compression.mime-types: application/json,text/html,text/xml,text/plain,application/javascript,text/css

APP_NAME: dolly
APP_VERSION: ${application.version}

### SPRING ###
spring:
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=d26dbfl023.test.local)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=DOLLYU)(INSTANCE_NAME=ccuf03)(UR=A)(SERVER=DEDICATED)))
    username: DOLLY_U
    ? password

#### APP DB ####
? app.datasource.onsHosts

#### NEW FREG-SECURITY #####
freg.security.oidc:
  idp:
    openAm:
      ? clientId
      ? clientSecret
      ? hostUrl
      ? issuerUrl
      ? jwksUrl
      loginUrl: ${freg.security.oidc.idp.openAm.hostUrl}/oauth2/authorize
      authorizationUrl: ${freg.security.oidc.idp.openAm.hostUrl}/oauth2/access_token
  auth:
    codeFlow:
      enabled: true
    idToken:
      refresh-on-seconds-left: 300
      cookie-enabled: true
      header-enabled: true
      validation:
        type: refreshing

providers:
  tpsf:
    url: http://localhost:8050
  sigrun:
    url: http://localhost:8040


### CORS ###
dolly.security.cors.origins: http://localhost:3050,http://localhost:3000
