# Default properties uses H2 Database
# H2 console at http://localhost:8080/h2-console

# Datasource
spring:
  datasource:
    url: jdbc:h2:mem:dollyDB
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    enabled: false
    url: jdbc:h2:mem:dollyDB;DB_CLOSE_DELAY=-1
    user: sa
    password:
  h2:
    console:
      enabled: true

