server.port: 8080

APP_NAME: dolly
APP_VERSION: ${application.version}

### SPRING ###
spring:
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url:
    username:
    password:

#### APP DB ####
app.datasource.onsHosts:


#### NEW FREG-SECURITY #####
freg.security.oidc:
  idp:
    openAm:
      clientId:
      clientSecret:
      hostUrl:
      issuerUrl:
      jwksUrl:
      loginUrl: ${freg.security.oidc.idp.openAm.hostUrl}/oauth2/authorize
      authorizationUrl: ${freg.security.oidc.idp.openAm.hostUrl}/oauth2/access_token
  auth:
    codeFlow:
      enabled: true
    idToken:
      refresh-on-seconds-left: 300
      cookie-enabled: true
      header-enabled: false
      validation:
          type: refreshing

### ABAC ###
#no.nav.abac:
#  url: ${no.nav.abac.url}
#  systemuser:
#    username: ${dolly.username}
#    password: ${dolly.password}


### TPSF ###
tpsf.server.url:

### SIGRUN ###
sigrun.server.url:

### CORS ###
dolly.security.cors.origins:

