CLIENT_SECRET: ${azure.app.client.secret}
AAD_ISSUER_URI: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b

providers:
  tpsf:
    url: https://tps-forvalteren-u2.nais.preprod.local
#    url: http://localhost:8050

#spring:
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true