# H2 console at http://localhost:8080/h2-console
server.port: 8080

APP_NAME: dolly
FASIT_ENVIRONMENT_NAME: localhost
application.version: @application.version@

spring:
  datasource:
    url: jdbc:h2:mem:dollyDB
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    enabled: false
    url: jdbc:h2:mem:dollyDB;DB_CLOSE_DELAY=-1
    user: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2

### ABAC ###
no.nav.abac:
    url: https://wasapp-t4.adeo.no/asm-pdp/authorize
    systemuser:
      username: srvnorg2_u
      password: 4bcW4E4Qg2pP1xO

#### NEW FREG-SECURITY #####
freg.security.oidc:
  idp:
    openAm:
      clientId: dolly-localhost
      clientSecret: KLNebXvbi4-gSPMzWrlNK7LPT93voNjm
      hostUrl: https://isso-t.adeo.no:443/isso
      issuerUrl: https://isso-t.adeo.no:443/isso/oauth2
      loginUrl: https://isso-t.adeo.no/isso/oauth2/authorize
      authorizationUrl: https://isso-t.adeo.no/isso/oauth2/access_token
      jwksUrl: https://isso-t.adeo.no/isso/oauth2/connect/jwk_uri
  auth:
    codeFlow:
      enabled: true
    idToken:
      refresh-on-seconds-left: 300
      cookie-enabled: true
      header-enabled: false
      validation:
          type: refreshing


### TPSF ###
tpsf.server.url: https://tps-forvalteren-u2.nais.preprod.local

### SIGRUN ###
sigrun.server.url: http://localhost:8040

### CORS ###
dolly.security.cors.origins: http://localhost:3050,http://localhost:3000
