server.port: 8080

APP_NAME: dolly
application.version: @application.version@

spring:
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
  flyway:
    enabled: true
    url: jdbc:h2:mem:dollyDB;DB_CLOSE_DELAY=-1
  main:
    banner-mode: off

#### NEW FREG-SECURITY #####
freg.security.oidc:
  idp:
    openAm:
      clientId:
      clientSecret:
      hostUrl:
      issuerUrl:
      jwksUrl:
      loginUrl: ${freg.security.oidc.idp.openAm.hostUrl}/oauth2/authorize
      authorizationUrl: ${freg.security.oidc.idp.openAm.hostUrl}/oauth2/access_token
  auth:
    codeFlow:
      enabled: true
    idToken:
      refresh-on-seconds-left: 300
      cookie-enabled: true
      header-enabled: false
      validation:
          type: refreshing

### ABAC ###
#no.nav.abac:
#  url: ${no.nav.abac.url}
#  systemuser:
#    username: ${dolly.username}
#    password: ${dolly.password}



### TPSF ###
tpsf.server.url: https://tps-forvalteren-u2.nais.preprod.local

### SIGRUN ###
sigrun.server.url: http://localhost:8040

### CORS ###
dolly.security.cors.origins: http://localhost:3050,http://localhost:3000

