
consumers:
  testnav-helsepersonell-service:
    url: https://testnav-helsepersonell-service.dolly.svc.cluster.local
  testnav-organisasjon-forvalter:
    url: https://testnav-organisasjon-forvalter.dolly.svc.cluster.local
  testnav-inntektsmelding-service:
    url: https://testnav-inntektsmelding-service.dolly.svc.cluster.local
  testnav-pdl-forvalter:
    url: https://testnav-pdl-forvalter.dev.intern.nav.no
